# docker compose v2 file
#
# https://docs.docker.com/compose/compose-file/

name: londiste-combo

services:
  test-pg15:
    container_name: "test-pg15"
    build:
      context: .
      dockerfile: etc/Dockerfile.combo
      args:
        PG: "15"
        PY: "3.11"
    volumes:
      - type: bind
        read_only: true
        source: .
        target: /repo
    deploy:
      mode: global
    command: ["./run.sh"]

  test-pg14:
    container_name: "test-pg14"
    build:
      context: .
      dockerfile: etc/Dockerfile.combo
      args:
        PG: "14"
        PY: "3.10"
    volumes:
      - type: bind
        read_only: true
        source: .
        target: /repo
    deploy:
      mode: global
    command: ["./run.sh"]

  test-pg18:
    container_name: "test-pg18"
    build:
      context: .
      dockerfile: etc/Dockerfile.combo
      args:
        PG: "18"
        PY: "3.14"
    volumes:
      - type: bind
        read_only: true
        source: .
        target: /repo
    deploy:
      mode: global
    command: ["./run.sh"]

